[package]
name = "datatoad"
version = "0.1.0"
edition = "2024"

[profile.release]
debug = true

[dependencies]
columnar = "0.11"
regex = "1.11.1"
mimalloc = { version = "0.1.48", features = ["v3"] }
simd-csv = "0.10.3"
timely_bytes = "0.25.1"
timely_communication = "0.25.1"
